### ISSUE TITLE
Why the start day is -1 ? 

### ISSUE THREAD

**Issue by IanaKhitsko** [gurland/euro-diffusion#14]
https://github.com/gurland/euro-diffusion/blob/9a671950bdd55b2d804a129308226f0222664d1a/main.py#L41

Why the start day is -1 ? (not 0) ? Doesn't it add additional day ?

**Comment by gurland** [comment]
Thanks for your issue! It wasn't adding additional day to the result however execution order of different algorithm steps was ambiguous and after moving a for-loop beneath next day simulation we achieved better readability and rational initial day number, so to say day 0.
